### ISSUE TITLE
GAS directives' highlighting aren't correct

### ISSUE THREAD

**Issue by Raverstern** [ARM9/arm-syntax-vim#1]
Hello there.

In the `include/gas_directives.vim`, the `syn keyword` is used to group those directives, which are all prefixed by dots. But the `.` character isn't within the default `iskeyword` option for `.s` or `.S` files (the `syn keyword` requires that) , and therefore all the highlighting of GAS directives are incorrect.

I suggest you to add code to supplement the `iskeyword` option with the `.` character, or to change those `syn keyword` into `syn match`.

**Comment by ARM9** [comment]
Thanks for the bug report, it should be fixed now.
