### ISSUE TITLE
Bug: regex of armv6 VFP/NEON registers

### ISSUE THREAD

**Issue by Raverstern** [ARM9/arm-syntax-vim#2]
Hi there.

The current regular expression of VFP/NEON registers in `armv6_base_syntax.vim` incorrectly matches labels as follows:
![wrong](https://cloud.githubusercontent.com/assets/8509855/10556932/d8da0f06-74c7-11e5-9f21-91d7c7cabd60.png)

Since the `,` isn't within the `iskeyword` set, the problem can be solved by appending a `\>` on the wrong regular expression.

Please try it and fix it.

**Comment by ARM9** [comment]
Thanks for catching that, PR merged. I had some configurations in my vimrc that affected the syntax and masked issues like this one, will see if I can spot any other glaring issues.
