### ISSUE TITLE
svr is not highlighted as an instruction.

### ISSUE THREAD

**Issue by Plotnus** [ARM9/arm-syntax-vim#6]
svr is not highlighted as an instruction.
PR incoming.

**Comment by Plotnus** [comment]
I'm not sure svr is an instruction anymore.
I tried compiling with it and it failed.

In a book I read "(If you are programming in A32 then SVR should be used. However, it is likely that any compiler you are using will compile SWI correctly.)" That is why I believe svr is supposed to be a valid instruction.

**Comment by ARM9** [comment]
I recognize this instruction but I can't find anything on it, iirc it's the old mnemonic for swi? Regardless, this syntax only supports the gnu assembler for now, which doesn't accept SVR.

**Comment by Plotnus** [comment]
Yea I'm not sure about it either. I'll just close this out for now.
